# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-15 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='sex',
            field=models.CharField(max_length=32),
        ),
    ]
